package main

// T017 [P] [US2] non-stream HTTP caller and strict span-mapper tests: omitted
// `temperature`, logprobs=true, top-2 alternatives, reasoning/content suffix
// variants, UTF-8 bytes, token-boundary failures, short answers, unavailable
// reasons, 64 MiB limit, retry classification, and raw-response privacy.

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"math"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
)

// --- span mapper: feature extraction over crafted token sequences ---

func TestUtilityMapFinalSignalBasic(t *testing.T) {
	// content == reconstructed bytes (no reasoning prefix); final answer is the
	// trailing suffix "Oslo". Each final token has two finite alternatives.
	tokens := []utilityLogprobToken{
		{Token: "Os", Bytes: []byte("Os"), Logprob: -0.1, Top1: -0.1, Top2: -2.0},
		{Token: "lo", Bytes: []byte("lo"), Logprob: -0.2, Top1: -0.2, Top2: -2.1},
	}
	sig, err := utilityMapFinalSignal("Oslo", tokens)
	if err != nil {
		t.Fatalf("map: %v", err)
	}
	if sig.Status != "available" {
		t.Fatalf("status = %s reason=%s, want available", sig.Status, sig.Reason)
	}
	if sig.FinalTokenCount != 2 || sig.FinalByteStart != 0 || sig.FinalByteEnd != 4 {
		t.Fatalf("span = [%d,%d) n=%d, want [0,4) n=2", sig.FinalByteStart, sig.FinalByteEnd, sig.FinalTokenCount)
	}
	if len(sig.Features) != 3 {
		t.Fatalf("features len = %d, want 3", len(sig.Features))
	}
	// final_mean_logprob = (-0.1 + -0.2)/2 = -0.15
	// p10 (n=2, index ceil(0.2)-1 = 0) = -0.2 (nearest-rank 10th percentile)
	// margin mean = (1.9 + 1.9)/2 = 1.9
	if sig.Features[0] < -0.16 || sig.Features[0] > -0.14 {
		t.Fatalf("mean logprob = %v, want ~-0.15", sig.Features[0])
	}
	if sig.Features[1] < -0.21 || sig.Features[1] > -0.19 {
		t.Fatalf("p10 logprob = %v, want ~-0.20", sig.Features[1])
	}
	if sig.Features[2] < 1.89 || sig.Features[2] > 1.91 {
		t.Fatalf("margin = %v, want ~1.90", sig.Features[2])
	}
}

func TestUtilityMapFinalSignalReasoningPrefix(t *testing.T) {
	// content includes a thinking prefix; final answer "Oslo" is the trailing
	// suffix of both content and the reconstructed bytes.
	content := "<think>let me think</think>\nOslo"
	tokens := []utilityLogprobToken{
		{Token: "<think>", Bytes: []byte("<think>"), Logprob: -1.0, Top1: -1.0, Top2: -3.0},
		{Token: "let me think", Bytes: []byte("let me think"), Logprob: -0.5, Top1: -0.5, Top2: -2.5},
		{Token: "</think>\n", Bytes: []byte("</think>\n"), Logprob: -0.8, Top1: -0.8, Top2: -2.8},
		{Token: "Os", Bytes: []byte("Os"), Logprob: -0.1, Top1: -0.1, Top2: -2.0},
		{Token: "lo", Bytes: []byte("lo"), Logprob: -0.2, Top1: -0.2, Top2: -2.1},
	}
	sig, err := utilityMapFinalSignal(content, tokens)
	if err != nil {
		t.Fatalf("map: %v", err)
	}
	if sig.Status != "available" {
		t.Fatalf("status = %s reason=%s, want available", sig.Status, sig.Reason)
	}
	if sig.FinalTokenCount != 2 {
		t.Fatalf("final token count = %d, want 2", sig.FinalTokenCount)
	}
	if sig.FinalText != "Oslo" {
		t.Fatalf("final answer = %q, want Oslo", sig.FinalText)
	}
}

func TestUtilityMapFinalSignalUnavailableReasons(t *testing.T) {
	cases := []struct {
		name    string
		content string
		tokens  []utilityLogprobToken
		want    string
	}{
		{
			name:    "content not suffix of generated bytes",
			content: "Oslo", // generated bytes reconstruct to "Oslovakia"
			tokens: []utilityLogprobToken{
				{Token: "Oslo", Bytes: []byte("Oslo"), Logprob: -0.1, Top1: -0.1, Top2: -2.0},
				{Token: "vakia", Bytes: []byte("vakia"), Logprob: -0.2, Top1: -0.2, Top2: -2.1},
			},
			want: "content_not_generated_suffix",
		},
		{
			name:    "final answer empty",
			content: "<think>no answer</think>", // nothing after the closing tag
			tokens: []utilityLogprobToken{
				{Token: "<think>no answer</think>", Bytes: []byte("<think>no answer</think>"), Logprob: -0.1, Top1: -0.1, Top2: -2.0},
			},
			want: "empty_final",
		},
		{
			name:    "missing top2 alternative",
			content: "Oslo",
			tokens: []utilityLogprobToken{
				{Token: "Os", Bytes: []byte("Os"), Logprob: -0.1, Top1: -0.1, Top2: 0}, // Top2 zero means absent
				{Token: "lo", Bytes: []byte("lo"), Logprob: -0.2, Top1: -0.2, Top2: -2.1},
			},
			want: "missing_top2",
		},
		{
			name:    "non-finite logprob",
			content: "Oslo",
			tokens: []utilityLogprobToken{
				{Token: "Os", Bytes: []byte("Os"), Logprob: -0.1, Top1: -0.1, Top2: -2.0},
				{Token: "lo", Bytes: []byte("lo"), Logprob: nan(), Top1: -0.2, Top2: -2.1},
			},
			want: "non_finite_probability",
		},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			sig, err := utilityMapFinalSignal(c.content, c.tokens)
			if err != nil {
				t.Fatalf("map: %v", err)
			}
			if sig.Status != "unavailable" {
				t.Fatalf("status = %s, want unavailable", sig.Status)
			}
			if sig.Reason != c.want {
				t.Fatalf("reason = %s, want %s", sig.Reason, c.want)
			}
		})
	}
}

func TestUtilityMapFinalSignalUTF8AndBoundary(t *testing.T) {
	// UTF-8 multibyte content: byte offsets must be token boundaries. The final
	// answer "答案：北京" is the trailing suffix after the thinking delimiter.
	content := "<think>思考</think>\n答案：北京"
	tokens := []utilityLogprobToken{
		{Token: "<think>", Bytes: []byte("<think>"), Logprob: -0.3, Top1: -0.3, Top2: -1.5},
		{Token: "思考", Bytes: []byte("思考"), Logprob: -0.5, Top1: -0.5, Top2: -2.0},
		{Token: "</think>\n", Bytes: []byte("</think>\n"), Logprob: -0.8, Top1: -0.8, Top2: -2.5},
		{Token: "答案：", Bytes: []byte("答案："), Logprob: -0.3, Top1: -0.3, Top2: -1.5},
		{Token: "北京", Bytes: []byte("北京"), Logprob: -0.1, Top1: -0.1, Top2: -1.2},
	}
	sig, err := utilityMapFinalSignal(content, tokens)
	if err != nil {
		t.Fatalf("map: %v", err)
	}
	if sig.Status != "available" {
		t.Fatalf("status = %s reason=%s, want available", sig.Status, sig.Reason)
	}
	// final "答案：北京" spans bytes [22,37): "<think>"=7 + "思考"=6 + "</think>\n"=9.
	if sig.FinalByteStart != 22 || sig.FinalByteEnd != 37 {
		t.Fatalf("span = [%d,%d), want [22,37)", sig.FinalByteStart, sig.FinalByteEnd)
	}
	if sig.FinalLengthStratum != "2-4" {
		t.Fatalf("stratum = %s, want 2-4", sig.FinalLengthStratum)
	}
}

// --- HTTP caller: request shape and parsing ---

func TestUtilityLogprobCallerRequestShape(t *testing.T) {
	var gotBody map[string]any
	var gotHeaders http.Header
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		raw, _ := io.ReadAll(r.Body)
		_ = json.Unmarshal(raw, &gotBody)
		gotHeaders = r.Header
		w.Write([]byte(`{"choices":[{"message":{"content":"Oslo"},"logprobs":{"content":[
			{"token":"Os","bytes":[79,115],"logprob":-0.1,"top_logprobs":[{"token":"Os","bytes":[79,115],"logprob":-0.1},{"token":"No","bytes":[78,111],"logprob":-2.0}]},
			{"token":"lo","bytes":[108,111],"logprob":-0.2,"top_logprobs":[{"token":"lo","bytes":[108,111],"logprob":-0.2},{"token":"mo","bytes":[109,111],"logprob":-2.1}]}
		]}}],"usage":{"prompt_tokens":10,"completion_tokens":2}}`))
	}))
	defer srv.Close()

	caller, err := utilityNewLogprobCaller(utilityLogprobCallerConfig{
		BaseURL: srv.URL, Model: "test-model", MaxTokens: 8000, MaxModelLen: utilityMaxModelLen,
	})
	if err != nil {
		t.Fatalf("new caller: %v", err)
	}
	completion, err := caller.complete(context.Background(), "sys", "user")
	if err != nil {
		t.Fatalf("complete: %v", err)
	}
	// temperature must be omitted from the wire shape.
	if _, has := gotBody["temperature"]; has {
		t.Fatalf("temperature field must be omitted, got %v", gotBody["temperature"])
	}
	if gotBody["logprobs"] != true {
		t.Fatalf("logprobs = %v, want true", gotBody["logprobs"])
	}
	if gotBody["top_logprobs"] != float64(2) {
		t.Fatalf("top_logprobs = %v, want 2", gotBody["top_logprobs"])
	}
	if gotBody["stream"] != false {
		t.Fatalf("stream = %v, want false", gotBody["stream"])
	}
	if completion.Content != "Oslo" || len(completion.Tokens) != 2 {
		t.Fatalf("completion = %+v, want content Oslo with 2 tokens", completion)
	}
	if completion.Usage.InputTokens != 10 || completion.Usage.OutputTokens != 2 {
		t.Fatalf("usage = %+v, want 10/2", completion.Usage)
	}
	if gotHeaders.Get("Authorization") != "" {
		t.Fatalf("empty key must not set Authorization header")
	}
}

func TestUtilityLogprobCallerAuthorization(t *testing.T) {
	var gotAuth string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotAuth = r.Header.Get("Authorization")
		w.Write([]byte(`{"choices":[{"message":{"content":"x"}}],"usage":{"prompt_tokens":1,"completion_tokens":1}}`))
	}))
	defer srv.Close()
	caller, err := utilityNewLogprobCaller(utilityLogprobCallerConfig{BaseURL: srv.URL, Model: "m", APIKey: "sk-test"})
	if err != nil {
		t.Fatal(err)
	}
	if _, err := caller.complete(context.Background(), "s", "u"); err != nil {
		t.Fatal(err)
	}
	if gotAuth != "Bearer sk-test" {
		t.Fatalf("authorization = %q, want Bearer sk-test", gotAuth)
	}
}

func TestUtilityLogprobCallerResponseTooLarge(t *testing.T) {
	// Body larger than the 64 MiB limit fails closed as response_too_large and
	// must not be retried.
	big := strings.Repeat("x", utilityResponseLimit+1)
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte(big))
	}))
	defer srv.Close()
	caller, err := utilityNewLogprobCaller(utilityLogprobCallerConfig{BaseURL: srv.URL, Model: "m"})
	if err != nil {
		t.Fatal(err)
	}
	_, err = caller.complete(context.Background(), "s", "u")
	if err == nil || !strings.Contains(err.Error(), "too large") {
		t.Fatalf("expected response_too_large error, got %v", err)
	}
}

func TestUtilityHTTPStatusClassification(t *testing.T) {
	cases := []struct {
		code      int
		want      utilityFailureReason
		retryable bool
	}{
		{http.StatusOK, "", false},
		{http.StatusTooManyRequests, utilityFailureHTTP429, true},
		{http.StatusInternalServerError, utilityFailureHTTP5xx, true},
		{http.StatusBadGateway, utilityFailureHTTP5xx, true},
		{http.StatusBadRequest, utilityFailureHTTP4xx, false},
		{http.StatusUnauthorized, utilityFailureHTTP4xx, false},
		{http.StatusRequestEntityTooLarge, utilityFailureHTTP4xx, false},
	}
	for _, c := range cases {
		reason, retryable := utilityClassifyHTTPStatus(c.code)
		if reason != c.want || retryable != c.retryable {
			t.Fatalf("status %d = (%s,%v), want (%s,%v)", c.code, reason, retryable, c.want, c.retryable)
		}
	}
}

func TestUtilityRetryExecutor(t *testing.T) {
	attempts := 0
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		attempts++
		if attempts < 2 {
			w.WriteHeader(http.StatusTooManyRequests)
			w.Write([]byte(`{"error":"rate limited"}`))
			return
		}
		w.Write([]byte(`{"choices":[{"message":{"content":"ok"}}],"usage":{"prompt_tokens":1,"completion_tokens":1}}`))
	}))
	defer srv.Close()
	caller, err := utilityNewLogprobCaller(utilityLogprobCallerConfig{BaseURL: srv.URL, Model: "m"})
	if err != nil {
		t.Fatal(err)
	}
	completion, err := caller.complete(context.Background(), "s", "u")
	if err != nil {
		t.Fatalf("complete with retry: %v", err)
	}
	if attempts != 2 || completion.Content != "ok" {
		t.Fatalf("attempts=%d completion=%q, want 2 retries then ok", attempts, completion.Content)
	}
}

func TestUtilityRetryExhaustion(t *testing.T) {
	attempts := 0
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		attempts++
		w.WriteHeader(http.StatusServiceUnavailable)
		w.Write([]byte(`{"error":"busy"}`))
	}))
	defer srv.Close()
	caller, err := utilityNewLogprobCaller(utilityLogprobCallerConfig{BaseURL: srv.URL, Model: "m"})
	if err != nil {
		t.Fatal(err)
	}
	if _, err := caller.complete(context.Background(), "s", "u"); err == nil {
		t.Fatal("exhausted retries must error")
	}
	if attempts != utilityMaxAttempts {
		t.Fatalf("attempts=%d, want %d", attempts, utilityMaxAttempts)
	}
}

func TestUtilityRetryNonRetryable(t *testing.T) {
	attempts := 0
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		attempts++
		w.WriteHeader(http.StatusBadRequest)
		w.Write([]byte(`{"error":"bad"}`))
	}))
	defer srv.Close()
	caller, err := utilityNewLogprobCaller(utilityLogprobCallerConfig{BaseURL: srv.URL, Model: "m"})
	if err != nil {
		t.Fatal(err)
	}
	if _, err := caller.complete(context.Background(), "s", "u"); err == nil {
		t.Fatal("non-retryable 4xx must error")
	}
	if attempts != 1 {
		t.Fatalf("attempts=%d, want 1 (no retry on 4xx)", attempts)
	}
}

func TestUtilityRawResponsePrivacy(t *testing.T) {
	// Failure errors must not embed the raw provider body or endpoint.
	secret := "secret-upstream-body-xyz"
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusBadRequest)
		w.Write([]byte(`{"error":"` + secret + `"}`))
	}))
	defer srv.Close()
	caller, err := utilityNewLogprobCaller(utilityLogprobCallerConfig{BaseURL: srv.URL, Model: "m"})
	if err != nil {
		t.Fatal(err)
	}
	_, err = caller.complete(context.Background(), "s", "u")
	if err == nil {
		t.Fatal("expected error")
	}
	if strings.Contains(err.Error(), secret) {
		t.Fatalf("failure error leaked raw provider body: %v", err)
	}
	if strings.Contains(err.Error(), srv.URL) {
		t.Fatalf("failure error leaked endpoint: %v", err)
	}
}

// --- helpers ---

func nan() float64 { return math.NaN() }

var _ = bytes.MinRead // keep bytes import
var _ = fmt.Sprintf
